name: "Release swap and asb"

on:
  release:
    types: [created]

jobs:
  release:
    name: Release swap
    strategy:
      matrix:
        include:
          - bin: swap
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive_ext: tar
          - bin: swap
            target: x86_64-apple-darwin
            os: macos-latest
            archive_ext: tar
          - bin: swap
            target: x86_64-pc-windows-msvc
            os: windows-latest
            archive_ext: zip
          - bin: asb
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive_ext: tar
          - bin: asb
            target: x86_64-apple-darwin
            os: macos-latest
            archive_ext: tar
          - bin: asb
            target: x86_64-pc-windows-msvc
            os: windows-latest
            archive_ext: zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tagged commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.BOTTY_GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v1.2.0

      - name: Build ${{ matrix.target }} ${{ matrix.bin }} release binary
        run: cargo build --target=${{ matrix.target }} --release --package swap --bin ${{ matrix.bin }}

      - name: Smoke test the binary
        run: target/${{ matrix.target }}/release/${{ matrix.bin }} --help

      # Remove once python 3 is the default
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - id: create-archive-name
        shell: python # Use python to have a prettier name for the archive on Windows.
        run: |
          import platform
          os_info = platform.uname()

          arch = os_info.machine

          triple = "${{ matrix.target }}".split("-")
          arch = triple[0]

          archive_name=f'${{ matrix.bin }}_${{ github.event.release.tag_name }}_{os_info.system}_{arch}.${{ matrix.archive_ext }}'

          print(f'::set-output name=archive::{archive_name}')

      - name: Pack macos archive
        if: matrix.os == 'macos-latest'
        shell: bash
        run: gtar -C ./target/${{ matrix.target }}/release --create --file=${{ steps.create-archive-name.outputs.archive }} ${{ matrix.bin }}

      - name: Pack linux archive
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: tar -C ./target/${{ matrix.target }}/release --create --file=${{ steps.create-archive-name.outputs.archive }} ${{ matrix.bin }}

      - name: Pack windows archive
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.bin }}.exe ./${{ matrix.bin }}.exe
          7z a -tzip ${{ steps.create-archive-name.outputs.archive }} ./${{ matrix.bin }}.exe

      - name: Upload archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOTTY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.create-archive-name.outputs.archive }}
          asset_name: ${{ steps.create-archive-name.outputs.archive }}
          asset_content_type: application/gzip
